services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_packages:/piston/packages
      - piston_jobs:/piston/jobs
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 114.114.114.114
    environment:
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - http_proxy=http://host.docker.internal:7890
      - https_proxy=http://host.docker.internal:7890

volumes:
  piston_packages:
  piston_jobs:
